
import Header from "@/components/layout/Header";
import "./globals.scss";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="az">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
